spring.application.name=enrollment-service
server.port=8083

# PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5433}/${DB_NAME:cyberlearnix_enrollments}?options=-c%20timezone=UTC&timezone=UTC
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=5

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Swagger Configuration
springdoc.api-docs.path=/api/enrollments/v3/api-docs
# PayU Configuration
payu.merchant.key=${PAYU_MERCHANT_KEY:XidEdD}
payu.merchant.salt=${PAYU_SALT:4JPMTxOzkJMchiHLrdFcSgkcXTuzx1Bd}

# JWT Configuration
jwt.secret=${JWT_SECRET:cyberlearnix-secure-and-ultra-long-secret-key-for-jwt-signing-2026-highly-confidential-512-bit-compliant}
