---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cyberlearnix-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: cyberlearnix
    app.kubernetes.io/managed-by: Helm
data:
  {{- range $key, $value := .Values.appConfig }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
