spring.application.name=user-service
server.port=8081

# PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5433}/${DB_NAME:cyberlearnix_users}?options=-c%20timezone=UTC&timezone=UTC
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=5

# Redis Configuration
spring.data.redis.host=${REDIS_HOST:127.0.0.1}
spring.data.redis.port=${REDIS_PORT:6379}

# JWT Configuration
jwt.secret=${JWT_SECRET:cyberlearnix-secure-and-ultra-long-secret-key-for-jwt-signing-2026-highly-confidential-512-bit-compliant}
jwt.expiration=3600000
jwt.refreshExpiration=7200000

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${GMAIL_USER:cyberlearnixprivatelimited@gmail.com}
spring.mail.password=${GMAIL_APP_PASSWORD:wxhqcbzyjfwhnoic}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Resend Configuration
resend.api.key=${RESEND_API_KEY:re_D9Z67Xpi_4taQ24N4ptZ5nbe97TYNtFAz}

# Multipart / File Upload Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Cloudinary Configuration
cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME:dt6rxrpqr}
cloudinary.upload-preset=${CLOUDINARY_UPLOAD_PRESET:ml_default}
cloudinary.api-key=${CLOUDINARY_API_KEY:#{null}}
cloudinary.api-secret=${CLOUDINARY_API_SECRET:#{null}}

# Swagger Configuration
springdoc.api-docs.path=/api/auth/v3/api-docs
